#!/usr/bin/env python

from bacpypes.basetypes import PropertyIdentifier
from bacpypes.object import Object, OptionalProperty
from bacpypes.primitivedata import CharacterString

import time
import sys
import threading
import json
import argparse
from pdb import set_trace as bp
from rdflib import Namespace, Graph, Literal

from bacpypes.core import run as bacpypes_run

from brickbacnet.discovery import BacnetDiscovery
from brickbacnet.brickserver import BrickServer
from brickbacnet.namespaces import BACNET, BRICK_NS_TEMPLATE, OWL, RDF, RDFS

def str2ilist(s):
    s.replace(' ', '')
    return [int(c) for c in s.split(',')]

class BacnetConn(object):
    def __init__(self):
        parser = argparse.ArgumentParser(
            description="BACnet connector with Brick Server or something similar.",
        )
        parser.add_argument(
            "command", help="The command to run", choices=["discovery", "connector"],
        )
        args = parser.parse_args(sys.argv[1:2])
        getattr(self, args.command)()

    def discovery(self):
        parser = argparse.ArgumentParser(
            description="Record changes to the repository",
        )
        parser.register('type','ilist', str2ilist)
        parser.add_argument(
            "--bacpypes-ini",
            help="The location of BACpypes.ini",
            default="configs/BACpypes.ini",
        )
        parser.add_argument(
            "--brickbacnet-config",
            help="The location of brickbacnet config file in JSON.",
            default="configs/brickbacnet_config.json"
        )
        parser.add_argument(
            "--bacnet-devices-file",
            help="The target file to store bacnet devices' metadata.",
            default="results/bacnet_devices.json",
        )
        parser.add_argument(
            "--bacnet-objects-file",
            help="The target file to store bacnet objects' metadata.",
            default="results/bacnet_objects.json",
        )
        parser.add_argument(
            "--brickserver-config",
            help="The location of brickbacnet config file in JSON.",
            default="configs/brickserver_config.json"
        )
        parser.add_argument(
            "--register-brickserver",
            action="store_const",
            const=True,
            default=False,
            help="Regsiter discovered objects in a Brick Server",
        )
        parser.add_argument(
            "--register-plastser",
            action="store_const",
            const=True,
            default=False,
            help="Regsiter discovered objects in a Plaster Web Service (TODO)",
        )
        parser.add_argument(
            "--target-devices",
            default=None,
            help="Indicate the target devices for which you'd like to get objects. By default, brickbacnet queries all the discoverable devices. Comma-separated integers are accepted (e.g., --target-devices 505,506",
            type='ilist',
        )
        parser.add_argument(
            "--base-namespace",
            default='http://example.com#',
            help="The name space associated with discovered entities",
            type=str,
        )
        parser.add_argument(
            "--brick-version",
            default='1.0.3',
            help="Brick's version",
            type=str,
        )

        # Set parameters
        args = parser.parse_args(sys.argv[2:])
        self.BASE = Namespace(args.base_namespace)
        self.BRICK = Namespace(BRICK_NS_TEMPLATE.format(version=args.brick_version))
        with open(args.brickbacnet_config, 'r') as fp:
            brickbacnet_config = json.load(fp)
        self.property_filters = brickbacnet_config["property_filters"]

        # Set up threads for BACpypes
        bacnet_discovery = BacnetDiscovery(args.bacpypes_ini, brickbacnet_config)
        time.sleep(1)
        run_thread = threading.Thread(target=bacpypes_run)
        run_thread.daemon = True
        run_thread.start()

        # Discover BACnet devices
        devices = bacnet_discovery.discover_devices()
        with open(args.bacnet_devices_file, "w") as fp:
            json.dump(devices, fp, indent=4, sort_keys=True)

        # Discover BACnet objects for identified devices
        if args.target_devices:
            target_device_ids = args.target_devices
            target_devices = {dev_id: devices[dev_id] for dev_id in target_device_ids}
        else:
            target_devices = devices
        device_objs = bacnet_discovery.discover_objects(target_devices)
        with open(args.bacnet_objects_file, "w") as fp:
            json.dump(device_objs, fp, indent=4, sort_keys=True)

        # Serialize the discovered resources into an RDF graph
        g = self.make_brick_graph(target_devices, device_objs)

        # Register the identifeid devies and objects to Brick Server
        if args.register_brickserver:
            bs_config = json.load(open(args.brickserver_config, 'r'))
            self.brickserver = BrickServer(bs_config['hostname'], bs_config['jwt_token'])
            self.brickserver.register_graph(g)

    def _get_default_graph(self):
        g = Graph()
        g.bind('brick', self.BRICK)
        g.bind('bacnet', BACNET)
        g.bind('base', self.BASE)
        return g

    def make_brick_graph(self, devices, device_objs, target_file='results/b2b.ttl'):
        g = self._get_default_graph()
        for dev_props in devices.values():
            dev_id = dev_props['device_id']
            dev_uri = self.BASE[dev_id]
            g.add((dev_uri, RDF.type, BACNET.BACnet_Device))
            for prop, val in dev_props.items():
                if prop in ['device_id'] + self.property_filters:
                    continue
                g.add((dev_uri, BACNET[prop], Literal(val)))
            for obj_props in device_objs[int(dev_id)].values():
                obj_uri = self.BASE[obj_props['source_identifier']]
                g.add((obj_uri, RDF.type, self.BRICK.Point))
                g.add((dev_uri, self.BRICK.hasPoint, obj_uri))
                for prop, val in obj_props.items():
                    if prop in ['source_identifier'] + self.property_filters:
                        continue
                    g.add((obj_uri, BACNET[prop], Literal(val)))
        g.serialize(target_file, format='turtle')
        return g


    def connector(self):
        parser = argparse.ArgumentParser(
            description="Download objects and refs from another repository"
        )
        # NOT prefixing the argument with -- means it's not optional
        parser.add_argument("repository")
        args = parser.parse_args(sys.argv[2:])


if __name__ == "__main__":
    BacnetConn()
